name: Validation Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    name: "Validate action file"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ActionLint
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- -b .
          chmod +x ./actionlint
          mv ./actionlint /usr/local/bin/

      - name: Validate action.yml
        run: |
          actionlint action.yml