name: Validation Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    name: "Validate action file"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ActionLint
        run: |
          go install github.com/rhysd/actionlint/cmd/actionlint@latest

      - name: Validate action.yml
        run: |
          actionlint action.yml